projectName: binder-staging

binderhub:
  ingress:
    hosts:
      - staging.mybinder.org

  registry:
    prefix: gcr.io/binder-staging/r2d-aee37be-

  hub:
    url: https://hub.staging.mybinder.org

  jupyterhub:
    singleuser:
      memory:
        guarantee: 256M
        limit: 256M
      cpu:
        guarantee: 0.1
        limit: 0.5
    ingress:
      hosts:
        - hub.staging.mybinder.org
      tls:
        - secretName: kubelego-tls-jupyterhub-staging
          hosts:
            - hub.staging.mybinder.org

grafana:
  ingress:
    hosts:
      - grafana.staging.mybinder.org
    tls:
      - hosts:
          - grafana.staging.mybinder.org
        secretName: kubelego-tls-grafana
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://prometheus.staging.mybinder.org
          access: direct
          isDefault: true
          editable: false

prometheus:
  server:
    ingress:
      hosts:
        - prometheus.staging.mybinder.org
      tls:
        - hosts:
            - prometheus.staging.mybinder.org
          secretName: kubelego-tls-prometheus

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 104.197.11.66
    replicaCount: 2

static:
  ingress:
    hosts:
      - static.staging.mybinder.org

redirector:
  redirects:
    - type: host
      host:
        from: beta.staging.mybinder.org
        to: staging.mybinder.org
    - type: host
      host:
        from: docs.staging.mybinder.org
        to: mybinder.readthedocs.io
    - type: host
      host:
        from: playground.staging.mybinder.org
        to: play.nteract.io

matomo:
  enabled: true
  db:
    instanceName: binder-staging:us-central1:matomo
  trustedHosts:
    - staging.mybinder.org
  ingress:
    hosts:
      - staging.mybinder.org

eventsArchiver:
  sourceBucket: mybinder-staging-events-raw-export
  destinationBucket: mybinder-staging-events-archive


gitterGrafanaLogger:
  # Only run one copy of logger bot
  enabled: false